python train_prefix_gate.py \
  --model_ckpt ../../minjeong/unsupervised_ckpt/UCF_all_cnn_final_20260331_020353_wv5ldb2h.pkl \
  --pseudofile ../../minjeong/Unsup_labels/pseudo_labels_swap_90.npy \
  --conall_path ../../C2FPL/concat_UCF.npy \
  --nalist_path list/nalist_i3d.npy \
  --save_path prefix_gate_best.pt \
  --warmup_segments 5 \
  --tea_lr 1e-2 \
  --tea_steps_per_video 30 \
  --gate_epochs 15 \
  --label_smoothing