"""
ETCL Main - Compatible with C2FPL workflow

Workflow:
1. FIRST run: python generate_pseudo_labels.py 
   → Creates Unsup_labels/etcl_labels.npz

2. THEN run: python main_etcl.py
   → Loads saved labels and trains

This follows C2FPL's separated workflow.
"""

from torch.utils.data import DataLoader
import torch.optim as optim
import torch
import os
import numpy as np
from tqdm import tqdm
import argparse

# Import from C2FPL (these should exist in the same directory)
from dataset import UCFTestVideoDataset, UCFTrainSnippetDataset
from test import test
from model_etcl import Model_ETCL
from train_etcl import ETCLLoss, etcl_train_epoch, refine_pseudo_labels
from utillsv2_etcl import Concat_list_all_crop_feedback


def parse_args():
    parser = argparse.ArgumentParser(description='ETCL Training')
    
    # Basic
    parser.add_argument('--datasetname', type=str, default='UCF_ETCL')
    parser.add_argument('--max_epoch', type=int, default=50)
    parser.add_argument('--batch_size', type=int, default=128)
    parser.add_argument('--workers', type=int, default=0)
    parser.add_argument('--feature_size', type=int, default=2048)
    parser.add_argument('--modality', type=str, default='rgb')
    parser.add_argument('--lr', type=float, default=0.01)
    
    # Pseudo label file (generated by generate_pseudo_labels.py)
    parser.add_argument('--pseudofile', type=str, 
                        default='Unsup_labels/etcl_labels.npz',
                        help='Path to pseudo labels (npz or npy)')
    
    # ETCL hyperparameters
    parser.add_argument('--kl_weight', type=float, default=0.1,
                        help='Weight for KL divergence regularization')
    parser.add_argument('--temporal_weight', type=float, default=0.1,
                        help='Weight for temporal consistency')
    parser.add_argument('--annealing_epochs', type=int, default=10,
                        help='Epochs for KL annealing')
    parser.add_argument('--refinement_interval', type=int, default=10,
                        help='Epochs between pseudo label refinement')
    
    # Ablation flags
    parser.add_argument('--no_uncertainty_weighting', action='store_true',
                        help='Disable uncertainty-aware weighting')
    parser.add_argument('--no_refinement', action='store_true',
                        help='Disable iterative pseudo label refinement')
    
    parser.add_argument('--gt', default='list/gt-ucf-RTFM.npy', help='file of ground truth ')
    
    # Logging
    parser.add_argument('--use_wandb', action='store_true')
    
    return parser.parse_args()


def main():
    args = parse_args()
    
    print("=" * 60)
    print("ETCL: Evidential Temporal Consistency Learning")
    print("=" * 60)
    print(f"\nConfig:")
    print(f"  KL weight: {args.kl_weight}")
    print(f"  Temporal weight: {args.temporal_weight}")
    print(f"  Refinement interval: {args.refinement_interval}")
    print(f"  Uncertainty weighting: {not args.no_uncertainty_weighting}")
    
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"  Device: {device}")
    
    # Create directories
    os.makedirs('./ckpt', exist_ok=True)
    os.makedirs('./unsupervised_ckpt', exist_ok=True)
    
    # ========== Load Pseudo Labels ==========
    # These should be pre-generated by generate_pseudo_labels.py
    print(f"\nLoading pseudo labels from: {args.pseudofile}")
    
    try:
        num_labels, labels, confidence = Concat_list_all_crop_feedback(
            Test=False, create='False', args=args
        )
        print(f"  Labels: {num_labels} segments")
        print(f"  Abnormal ratio: {labels.float().mean().item():.4f}")
        print(f"  Mean confidence: {confidence.mean().item():.4f}")
    except FileNotFoundError as e:
        print(f"\nERROR: {e}")
        print("\nPlease run generate_pseudo_labels.py first:")
        print("  python generate_pseudo_labels.py --output Unsup_labels/etcl_labels.npz")
        return
    
    # Convert to numpy for manipulation
    labels_np = labels.cpu().numpy()
    confidence_np = confidence.cpu().numpy()
    
    # ========== Wandb ==========
    if args.use_wandb:
        import wandb
        wandb.login()
        wandb.init(project="ETCL-VAD", config=vars(args))
    
    # ========== Data Loaders ==========
    test_loader = DataLoader(
    UCFTestVideoDataset(
        conall_path="../C2FPL/Concat_test_10.npy",  # 경로 확인
        nalist_path="list/nalist_test_i3d.npy"      # 경로 확인
    ),
    batch_size=1,
    shuffle=False,
    num_workers=0,  # Windows
    pin_memory=False,
    drop_last=False
)
    
    train_loader = DataLoader(
        UCFTrainSnippetDataset(
            conall_path="../C2FPL/concat_UCF.npy",      # segment 단위 features
            pseudo_path="Unsup_labels/etcl_labels_labels.npy"  # pseudo labels
        ),
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=0,
        pin_memory=False,
        drop_last=True
    )

    # ========== Model ==========
    model = Model_ETCL(args.feature_size, hidden_dim=512, dropout=0.6)
    model = model.to(device)
    
    total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"\nModel: Model_ETCL ({total_params:,} params)")
    
    # ========== Optimizer ==========
    optimizer = optim.SGD(
        model.parameters(),
        lr=args.lr,
        weight_decay=5e-4,
        momentum=0.9,
        nesterov=True
    )
    scheduler = optim.lr_scheduler.MultiStepLR(
        optimizer, milestones=[15, 25], gamma=0.1
    )
    
    # ========== Loss ==========
    loss_fn = ETCLLoss(
        kl_weight=args.kl_weight,
        temporal_weight=args.temporal_weight,
        annealing_epochs=args.annealing_epochs,
        use_uncertainty_weighting=not args.no_uncertainty_weighting
    )
    
    # ========== Training ==========
    best_auc = 0.0
    test_info = {"epoch": [], "test_auc": [], "loss": []}
    
    # Initial evaluation
    auc, ap = test(test_loader, model, args, device)
    print(f"\nEpoch 0 (initial): AUC = {auc:.4f}, AP = {ap:.4f}")
    
    if args.use_wandb:
        wandb.log({'AUC': auc, 'AP': ap}, step=0)
    
    print("\n" + "=" * 60)
    print("Training")
    print("=" * 60)
    
    for epoch in tqdm(range(1, args.max_epoch + 1), total=args.max_epoch, dynamic_ncols=True):
        
        # Train epoch
        loss, predictions = etcl_train_epoch(
            train_loader, model, optimizer,
            labels_np, confidence_np, device,
            loss_fn, epoch
        )
        
        # Evaluate
        auc, ap = test(test_loader, model, args, device)
        
        test_info["epoch"].append(epoch)
        test_info["test_auc"].append(auc)
        test_info["loss"].append(loss)
        
        scheduler.step()
        
        # Logging
        print(f'\nEpoch {epoch}/{args.max_epoch}')
        print(f'  LR: {optimizer.param_groups[0]["lr"]:.6f}, Loss: {loss:.4f}')
        print(f'  AUC: {auc:.4f}, AP: {ap:.4f}')
        
        if args.use_wandb:
            wandb.log({
                'AUC': auc, 'AP': ap, 'loss': loss,
                'lr': optimizer.param_groups[0]["lr"]
            }, step=epoch)
        
        # Save best
        if auc > best_auc:
            best_auc = auc
            torch.save(model.state_dict(), './ckpt/etcl_best.pkl')
            print(f'  *** New best AUC: {best_auc:.4f} ***')
        
        # Pseudo label refinement
        if not args.no_refinement:
            if epoch % args.refinement_interval == 0 and epoch < args.max_epoch - args.refinement_interval:
                print(f'\n  [Refining pseudo labels at epoch {epoch}]')
                labels_np, confidence_np = refine_pseudo_labels(
                    labels_np, confidence_np, predictions,
                    confidence_threshold=0.7,
                    uncertainty_threshold=0.3
                )
    
    # Save final
    torch.save(model.state_dict(), f'./unsupervised_ckpt/{args.datasetname}_final.pkl')
    
    # Summary
    print("\n" + "=" * 60)
    print("Training Complete!")
    print("=" * 60)
    print(f"Best AUC: {best_auc:.4f}")
    print(f"Final AUC: {auc:.4f}")
    
    if args.use_wandb:
        wandb.run.name = args.datasetname
        wandb.finish()
    
    return best_auc


if __name__ == '__main__':
    main()
