python mainv2.py \
    --lossfn BCE \
    --optimizer SGD \
    --max-epoch 20 \
    --outer-epochs 1\
    --batch-size 128 \
    --lr 0.001\
    --feature-size 2048 \
    --gt list/gt-ucf-RTFM.npy\
    --datasetname UCF \
    --pseudofile Unsup_labels/pseudo_segment_labels.npy \
    --conall concat_UCF\
